"use client";

// frontend/src/components/duomath/PenroseFigure.jsx
//
// Phase 4 (integration-guide item 1) — geometric figures drawn by Penrose.
//
// Why a client component: Penrose compiles our trio (domain + style + substance)
// into an SVG in the browser and appends it to a DOM node, so it can only run
// where a DOM exists. The page loads it with next/dynamic `ssr: false` — the
// same rule the Mafs widget follows.
//
// Verified before shipping (node scripts/check-penrose-trios.mjs, run in CI):
// both trios compile, the optimizer converges, and every constraint is
// satisfied to ~1e-12. That check also measured the two risks the plan flagged:
// @penrose/core 3.3.1 ships NO WebAssembly (so no .wasm bundler pass and no
// `wasm-unsafe-eval` in the CSP), and there is no eval/new Function in its
// rendering path nor in mathjax-full (so the CSP stays exactly as it is).
//
// Safety: the SVG is generated by Penrose from OUR OWN trio — no user input ever
// reaches the Style program — and it is inserted as DOM nodes by Penrose's
// `diagram()`, never as an HTML string, so no sanitizer is needed here.

import { useEffect, useRef, useState } from "react";
import { PENROSE_TRIOS } from "@/lib/penroseTrios";

// A trio this small renders in ~1s; the cap only exists so a wedged optimizer
// can never leave the student staring at a spinner.
const RENDER_TIMEOUT_MS = 20000;

/** Penrose emits no progress events — poll the node until an <svg> appears. */
function waitForSvg(node, timeoutMs) {
  return new Promise((resolve, reject) => {
    const started = Date.now();
    const tick = () => {
      if (node.querySelector("svg")) return resolve(true);
      if (Date.now() - started > timeoutMs) return reject(new Error("Hết thời gian dựng hình."));
      return setTimeout(tick, 120);
    };
    tick();
  });
}

export default function PenroseFigure() {
  const [trioId, setTrioId] = useState(PENROSE_TRIOS[0].id);
  const [round, setRound] = useState(0);
  const [status, setStatus] = useState("drawing"); // drawing | ready | error
  const [error, setError] = useState("");

  const canvasRef = useRef(null);
  const trio = PENROSE_TRIOS.find((t) => t.id === trioId) ?? PENROSE_TRIOS[0];

  useEffect(() => {
    let cancelled = false;
    const node = canvasRef.current;
    if (!node) return undefined;
    node.replaceChildren();
    setStatus("drawing");
    setError("");

    (async () => {
      try {
        const { diagram } = await import("@penrose/core");
        if (cancelled) return;
        // No Style program here uses `import`, so the resolver is never called.
        const resolvePath = async () => undefined;
        await diagram(
          {
            domain: trio.domain,
            substance: trio.substance,
            style: trio.style,
            variation: `${trio.variation}-${round}`,
            excludeWarnings: [],
          },
          node,
          resolvePath,
          `duomath-${trio.id}`
        );
        await waitForSvg(node, RENDER_TIMEOUT_MS);
        if (!cancelled) setStatus("ready");
      } catch (err) {
        if (!cancelled) {
          setError(err?.message || String(err));
          setStatus("error");
        }
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [trio, round]);

  const busy = status === "drawing";

  const chip = (active) => ({
    fontSize: 12,
    fontWeight: 700,
    padding: "6px 11px",
    borderRadius: 999,
    cursor: "pointer",
    color: active ? "#04101f" : "#cbd5e1",
    background: active ? "linear-gradient(135deg,#67e8f9,#22d3ee)" : "rgba(30,41,59,0.7)",
    border: "1px solid rgba(148,163,184,0.25)",
  });

  return (
    <div style={{ border: "1px solid rgba(148,163,184,0.22)", borderRadius: 14, padding: 14, background: "rgba(9,14,30,0.6)" }}>
      <div style={{ display: "flex", gap: 8, flexWrap: "wrap", alignItems: "center", marginBottom: 10 }}>
        {PENROSE_TRIOS.map((option) => (
          <button key={option.id} onClick={() => setTrioId(option.id)} style={chip(option.id === trio.id)}>
            {option.title}
          </button>
        ))}
        <button
          onClick={() => setRound((r) => r + 1)}
          disabled={busy}
          style={{ ...chip(false), color: "#fde68a", background: "rgba(120,53,15,0.45)", border: "1px solid rgba(251,191,36,0.35)", cursor: busy ? "wait" : "pointer" }}
        >
          🔄 Đổi hình khác
        </button>
      </div>

      <div style={{ position: "relative", minHeight: 340 }}>
        <div ref={canvasRef} style={{ display: "flex", justifyContent: "center" }} />
        {busy && (
          <div style={{ position: "absolute", inset: 0, display: "flex", alignItems: "center", justifyContent: "center", color: "rgba(226,232,240,0.75)", fontSize: 13 }}>
            Đang dựng hình bằng Penrose… (lần đầu mất vài giây)
          </div>
        )}
      </div>

      <p style={{ margin: "8px 0 0", fontSize: 12.5, color: "rgba(226,232,240,0.7)", lineHeight: 1.7 }}>{trio.hint}</p>

      {status === "error" && (
        <div style={{ marginTop: 10, border: "1px solid rgba(248,113,113,0.4)", background: "rgba(127,29,29,0.25)", borderRadius: 10, padding: "8px 10px", fontSize: 12.5, color: "#fecaca" }}>
          <b>Không dựng được hình Penrose.</b> Phần còn lại của trang vẫn dùng bình thường — bấm “Đổi hình khác” để thử lại.
          <div style={{ marginTop: 4, fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace", fontSize: 11, opacity: 0.8, wordBreak: "break-word" }}>
            {error}
          </div>
        </div>
      )}
    </div>
  );
}
